=== lawrenceyim/BankApplication/src/main/resources/sax/Employees.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee_id" type="xs:long"/>
                            <xs:element name="bank_id" type="xs:long"/>
                            <xs:element name="first_name" type="xs:string"/>
                            <xs:element name="middle_name" type="xs:string"/>
                            <xs:element name="last_name" type="xs:string"/>
                            <xs:element name="position" type="xs:long"/>
                            <xs:element name="branch_id" type="xs:long"/>
                            <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lawrenceyim/BankApplication/src/main/resources/sax/EmployeesExample.xml
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Employees.xsd">
    <employee>
                <employee_id>1</employee_id>
                <bank_id>1</bank_id>
                <first_name>John</first_name>
                <middle_name>Doe</middle_name>
                <last_name>Bill</last_name>
                <position>1</position>
                <branch_id>1</branch_id>
                <email>johndoebill@gmail.com</email>
    </employee>
    <employee>
        <employee_id>2</employee_id>
        <bank_id>1</bank_id>
        <first_name>Dave</first_name>
        <middle_name>David</middle_name>
        <last_name>Dav</last_name>
        <position>2</position>
        <branch_id>1</branch_id>
        <email>davedaviddav@gmail.com</email>
    </employee>
</employees>
