=== lawrenceyim/BankApplication/src/main/resources/jaxb/EmployeeLoginDetails.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employee_login_details">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee_login_detail" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee_id" type="xs:long"/>
                            <xs:element name="username" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lawrenceyim/BankApplication/src/main/resources/jaxb/EmployeeLoginDetailExample.xml
<employee_login_details xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:noNamespaceSchemaLocation="EmployeeLoginDetails.xsd">
    <employee_login_detail>
        <employee_id>1</employee_id>
        <username>username1</username>
        <password>password1</password>
    </employee_login_detail>
    <employee_login_detail>
        <employee_id>2</employee_id>
        <username>username2</username>
        <password>password2</password>
    </employee_login_detail>
</employee_login_details>
